---
title: "brouillon_app_refuge"
author: "Thibault FUCHEZ"
date: "15/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(httr)
library(jsonlite)
library(readr)
```

## Première requète

```{r}
url_base = "https://www.refugerestrooms.org/api"
url_byloc = "/v1/restrooms/by_location"
url_bydate = "/v1/restrooms/by_date"
url_bysearch= "/v1/restrooms/search"
url_all="/v1/restrooms"
```

```{r}
urlLoc = paste0(url_base, url_byloc)
urlAll = paste0(url_base, url_all)
```

```{r}
source("funLib.r")

alldataReq <- function(pagemax){
  dfA <- data.frame()
  for (i in 1:pagemax){
    query <- list(per_page=100, page=i)
    dfB <- req_to_df("https://www.refugerestrooms.org/api/v1/restrooms",
                     query = query)
    dfA <- rbind(dfA, dfB)}
  return(dfA)
}

res = alldataReq(488)
```

```{r}
query <- list(lng="0.689797", lat="47.390185")
resp <- GET(urlLoc, query = query)
```

```{r}
resp
```

```{r}
headers(resp)
```

```{r}
http_error(resp)
```

```{r}
http_type(resp)
```

```{r}
# Shows raw data which is not structured and readable
jsonRespText<-content(resp,as="text") 
```

```{r}
# Structurised data in form of R vectors and lists
jsonRespParsed<-content(resp,as="parsed") 
```

```{r}
json_cont <- fromJSON(jsonRespText)
```

## Fonctions

```{r}
url_base = "https://www.refugerestrooms.org/api"
url_byloc = "/v1/restrooms/by_location"
url_bydate = "/v1/restrooms/by_date"
url_bysearch= "/v1/restrooms/search"
```

```{r}
urlLoc = paste0(url_base, url_byloc)
```

```{r}
req_to_df <- function(url, query){
  resp <- GET(urlLoc, query = query)
  jsonRespText <- content(resp,as="text")
  json_cont <- fromJSON(jsonRespText)
  return(json_cont)
}
```

```{r}
query <- list(lng="0.689797", lat="47.390185")
df2 <- req_to_df(urlLoc, query_Londres)
```

```{r}
df_transfo <- function(df){
  df %>% select(c(name, street, city, state, accessible, unisex, directions, comment))
} 
```

```{r}
df2 <- df_transfo(df)
```

```{r}
resp <- get
```

## Statistiques avec le Rdata (full df)

```{r}
res %>% group_by(country) %>% ggplot() +
  aes(x = fct_lump(fct_rev(fct_infreq(country)),10)) +
  geom_bar()+coord_flip()
```

## automatisation à partir de liste de villes

```{r}
source("funLib.r")
```

```{r}
worldcities <- read_csv("worldcities.csv")
```

```{r}
nrow(worldcities)
```

```{r}
city_Lat <- tablo_coord %>% filter(ville == "Tours") %>% pull(lat)
```

```{r}
city_Lng <- worldcities %>% filter(city_ascii == "Tours") %>% pull(lng)
```

```{r}
coord_city <- function(obj){
  city_lat <- tablo_coord %>% filter(ville == obj) %>% pull(lat)
  city_lng <- tablo_coord %>% filter(ville == obj) %>% pull(lng)
  return(list(city_lng, city_lat))
}
```

```{r}
test <- coord_city("Tours")
test
```

```{r}
liste_ville = list("Tours", "London")
```

```{r}
    variable <- switch(
      input$city,
      "Tours" = "Tours",
      "London" = "London"
    )
```

```{r}
display_map <- function(variable){
  coord <- coord_city(variable)
  map = bigmap(coord[[1]],coord[[2]])
  query <- list(lng=coord[[1]], lat=coord[[2]])
  df <- req_to_df(urlLoc, query = query)
  map %>% addMarkers(data = df, lng = ~longitude, lat = ~latitude)
}
```

```{r}
coord <- coord_city("Tours")
query <- list(lng=coord[[1]], lat=coord[[2]], per_page=100, ada = input$para[1], accessible = inut$para[2])
```


```{r}
  coord <- coord_city("Tours")
  map = bigmap(coord[[1]],coord[[2]])
  query <- list(lng=coord[[1]], lat=coord[[2]])
  df <- req_to_df(urlLoc, query = query)
  map %>% addMarkers(data = df, lng = ~longitude, lat = ~latitude)
```

```{r}
display_map("London")
```

```{r}
ville <- c("Tours", "London")
lat <- c(47.390185, 51.509865)
lng <- c(0.689797, -0.118092)
tablo_coord <- data.frame(ville = ville, lat = lat, lng=lng)
```

```{r}
ville_to_df <- function(variable){
  coord <- coord_city(variable)
  query <- list(lng=coord[[1]], lat=coord[[2]])
  req_to_df(urlLoc, query = query) %>% df_transfo()
  return(df_transfo)
}
```

```{r}
test <- ville_to_df("Tours")
```

```{r}
plopp <- df %>% filter(unisex == "TRUE")
```

```{r}
  get_table <- eventReactive({
    input$paraOk
  }, {
    df <- df %>% filter(input$paraOk == "TRUE")
  })
```

```{r}
  re <- eventReactive({
    input$paraOk
  }, {
    df <- df %>% filter(accessible == input$para[1])
  })
```

